---
- name: Install fish repository
  become: true
  ansible.builtin.apt_repository:
    repo: ppa:fish-shell/release-3
    state: present

- name: Install fish shell
  become: true
  ansible.builtin.apt:
    name: fish
    state: latest
    update_cache: yes
